### ISSUE TITLE
javax.persistence missing in classpath

### ISSUE THREAD

**Issue by wagenbm** [Book-Microservices-v2/chapter05#2]
Hi Moisés, when following chapter 5 I came accross the issue, that

`import javax.persistence.*;`

did not work (javax.persistence cannot be resolved). I added the following dependency in pom.xml which solved the problem:

               `<dependency>
			<groupId>javax.persistence</groupId>
			<artifactId>javax.persistence-api</artifactId>
			<version>2.2</version>
		</dependency>`

Did I miss something when following the book. I am not aware that it is mentioned at some place to add this dependency.

Thanks and best regards,
Matthias

**Comment by mechero** [comment]
Hi Matthias,

You're using a more recent JDK and Spring Boot than the one in the book. The last Java EE specs (used by Spring) have changed package names  from `javax.*` to `jakarta.*`. Try changing the package names, that should work.

But expect other deviations from the book's code, since new upgrades may have brought new ways of doing things.

Regards

**Comment by wagenbm** [comment]
Hi mechero,

Many thanks for your feedback. I followed your proposal which worked fine. I also removed the non-neccessary dependency on javax.\*. Is javax.\* still something which is required or is it completely replaced by jakarta.\*? I am asking, as I would have expected that javax.\* is marked as deprecated, but it is not.

Thanks and best regards,
Matthias
